Ignore certificate date verification
simplisafe/mbedTLS-iOS pull request #5
Opened 2021-05-25 19:34 UTC by harshakudoorss

2021-05-27 16:16 UTC, matthew-cox requested changes
Not quite right

2021-05-27 16:16 UTC, matthew-cox commented on Sources/libmbedtls/x509_crt.c
> +           from->day > (int)EXPIRY_DAY_MAX &&
I don't think this is quite correct. Try `5/21/49`:

`5 >= 4` True
`21 > 24` False
`49 == 49` True

True && False && True == False

2021-05-27 16:16 UTC, matthew-cox commented on Sources/libmbedtls/x509_crt.c
> +           from->day > (int)EXPIRY_DAY_MAX &&
Really I think it should be:

`((from->mon > EXPIRY_MONTH_MAX) || (from->mon == EXPIRY_MONTH_MAX)) && from->day > (int)EXPIRY_DAY_MAX) && to_year_computed == (int)EXPIRY_YEAR_MAX)`

2021-05-27 19:25 UTC, harshakudoorss commented on Sources/libmbedtls/x509_crt.c
> +           from->day > (int)EXPIRY_DAY_MAX &&
fixing this in the next commit.

2021-05-27 19:39 UTC, matthew-cox approved these changes
I think this handles the edge case correctly. A suggestion for extra readabilty is included (only because dates are hard...)

2021-05-27 19:39 UTC, matthew-cox commented on Sources/libmbedtls/x509_crt.c
> +            if(from->mon > EXPIRY_MONTH_MAX) {
This now is correct, but as I'm reading this trying to find edge cases my brain wants to know what happens when the year, month, and day are all equal.

It's slightly redundant, but for clarity: does it make sense to enumerate the three areas of concern directly in the code? Can we make the check more verbose by splitting them up?

```
if (to_year_computed == (int)EXPIRY_YEAR_MAX) {

    // month beyond the max month: should be one year earlier
    if (from->mon > EXPIRY_MONTH_MAX) {
        to_year_computed--;
    }
    // same month as the max month: need to check the day as well
    else if (from->mon == (int)EXPIRY_MONTH_MAX) {
    
        // day beyond the max day: should be one year earlier
        if (from->day > (int)EXPIRY_DAY_MAX) {
            to_year_computed--;
        }
    }
}
```

2021-05-28 18:28 UTC, harshakudoorss commented on Sources/libmbedtls/x509_crt.c
> +        ss_date_start_val = date_start_val;
@siddarthgandhi it does not make sense to set `ss_date_start_val = date_start_val` here since the if block is only executed if `date_start_val == 0x325e0d17`, so inside that block, we always know what the date_start_val is. It would make sense to set ss_date_start_val just outside the if block, on line 450, if we really want to track it. 

I'm not sure why @matthew-cox  wanted this value tracked - perhaps to see if there are other corruption modes that we have not encountered yet?

2021-05-28 18:41 UTC, matthew-cox commented on Sources/libmbedtls/x509_crt.c
> +        ss_date_start_val = date_start_val;
Yeah, that was the thought: there might be other certs with invalid dates and a pattern could be revealed by the analytics

2021-06-02 13:37 UTC, closed without merging